webapp/admin/views.py
from flask import Blueprint, render_template
from webapp.user.decorators import admin_required

blueprint = Blueprint("admin", __name__, url_prefix="/admin")


@blueprint.route('/')
@admin_required
def admin_index():  # Нет проверка на то, что залогиненый пользователь- админ, так как проверка происходит в декораторе в decorators
    title = "Панель управления"
    return render_template("admin/index.html", page_title=title)

webapp/user/views.py
from flask import Blueprint
from flask import Flask, render_template, flash, redirect, url_for
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from flask_login import login_user, logout_user, login_required, current_user
from webapp.db import db
from webapp.utils import get_redirect_target


blueprint = Blueprint("user", __name__, url_prefix="/users")  # user- название blueprint, __name__- имя подуля (можно оставлять так), url_prefix- все url в этом bleuprint будут начинаться с /users/variable


@blueprint.route("/login")
def login():
    if current_user.is_authenticated:
        return redirect(get_redirect_target())
    title = "Авторизация"
    login_form = LoginForm()
    return render_template("user/login.html", page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Вы успешно вошли на сайт')
            return redirect(get_redirect_target())

    flash('Неправильное имя пользователя или пароль')
    return redirect(url_for('user.login'))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash("Вы успешно разлогинились")
    return redirect(url_for('news.index'))


@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('news.index'))
    form = RegistrationForm()
    title = "Регистрация"
    return render_template('user/registration.html', page_title=title, form=form)


@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно зарегистрировались!')
        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в поле "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
    return redirect(url_for('user.register'))

webapp/templates/base.html
<!doctype html>
<html lang="ru">
    <head>
    <!-- Required meta tags- выбор кодировки utf-8, затем по-умолчанию выставляется размеры сайта -->
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

    <link rel="stylesheet"
    href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/atom-one-dark.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

    <title> {{ page_title }}</title>
    </head>
    <body>
    <div class="container">
        {% include "menu.html" %}   <!–– Вложить menu.html, отличие от block content заключается в том, что block content разный, а include фиксированный (я так понял) -->
    <h1>{{page_title}}</h1>
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Новости Python</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">  <!-- Если сжимать окно, то появится кнопка с вложенными функциями, это сделано для маленьких экранов-->
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">  <!-- То, что будет сжиматься в "сендвич" на маленьких экранах -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/"> Главная страница <span class="sr-only">(current)</span></a>
        </li>

      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Искать</button>
      </form>
      <ul class="navbar-nav">
        <li class="nav-item"></li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Привет, {{current_user.username}}</span>
    </li>
    {% if current_user.is_admin %}
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('admin.admin_index') }}">Админка</a>
  </li>
  {%endif%}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.logout') }}">Выйти</a>
      </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.register') }}">Регистрация</a>
        </li>
          <a class="nav-link" href="{{ url_for('user.login', next=request.full_path) }}">Войти</a>
        {% endif %}
        </li>
      </ul>
    </div>
  </nav>

webapp/templates/messages.html
{% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                        {{ message }}<br>
                    {% endfor %}
                </div>
                {% endif %}
            {% endwith %}